matrix_info_cam150:
  module: modules.matrix_info.matrix_info
  class: MatrixInfo
  MatrixInfo:
    in_adapter_mode: '''in_bat3d_cam150'''

label_cam150:
  module: modules.label.label
  class: LabelProcessing
  LabelProcessing:
    mode: '''label_to_yolotianxiaomo_cam150'''
    in_adapter_mode: '''in_bat3d_adapter_cam150'''

matrix_info_cam60:
  module: modules.matrix_info.matrix_info
  class: MatrixInfo
  MatrixInfo:
    in_adapter_mode: '''in_bat3d_cam60'''

label_cam60:
  module: modules.label.label
  class: LabelProcessing
  LabelProcessing:
    mode: '''label_to_yolotianxiaomo_cam60'''
    in_adapter_mode: '''in_bat3d_adapter_cam60'''

matrix_info_cam30:
  module: modules.matrix_info.matrix_info
  class: MatrixInfo
  MatrixInfo:
    in_adapter_mode: '''in_bat3d_cam30'''

label_cam30:
  module: modules.label.label
  class: LabelProcessing
  LabelProcessing:
    mode: '''label_to_yolotianxiaomo_cam30'''
    in_adapter_mode: '''in_bat3d_adapter_cam30'''
